# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :jekyll_plugins do
	gem "jekyll-redirect-from"
end

gem "jekyll-theme-opentoolbox", "~> 2.0"