# frozen_string_literal: true

source "https://rubygems.org"

group :jekyll_plugins do
    gem "jekyll-feed", "~> 0.6"
    gem "jekyll-sitemap"
    gem "jekyll-paginate"
    gem "jekyll-seo-tag"
	gem "jekyll-environment-variables"
	gem "jekyll-mentions"
	gem "jekyll-target-blank"
end

gem 'wdm', '>= 0.1.0' if Gem.win_platform?